apiVersion: 1

datasources:
  - name: Politics-Data
    type: mysql
    url: mysql-politics:3306
    user: ${{ secrets.MYSQL_USER }}
    database: politics_stats
    orgId: 1
    version: 1
    editable: true
    secureJsonData:
      password: ${{ secrets.MYSQL_PASSWORD }}
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
